version: "3.3"

services:
  dev-db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - laserpiente-db:/var/lib/postgresql/data

  app:
    build: .
    command: gunicorn "la_serpiente:create_app()" -b 0.0.0.0:80 --log-level=INFO
    ports:
      - "80:80"

volumes:
  laserpiente-db: {}
